export const allArtists = [
  {
    id: 1,
    name: "Nguyễn Văn A",
    specialty: "Tranh Đông Hồ",
    bio: "Nghệ nhân truyền thống với 30 năm kinh nghiệm vẽ tranh Đông Hồ. Đã giành nhiều giải thưởng quốc tế.",
    fullBio:
      "Tôi là một nghệ nhân truyền thống chuyên về tranh Đông Hồ. Với 30 năm kinh nghiệm, tôi đã dành cả cuộc đời để bảo tồn và phát triển nghệ thuật này. Tôi tin rằng tranh Đông Hồ không chỉ là một tác phẩm nghệ thuật mà còn là một phần quan trọng của di sản văn hóa Việt Nam.",
    image: "/placeholder.svg",
    coverImage: "/placeholder.svg",
    location: "Hà Nội",
    followers: 1234,
    rating: 4.9,
    verified: true,
    email: "nguyenvana@example.com",
    website: "nguyenvana.com",
    specialtyId: "painting",
    works: [
      { id: 1, title: "Tác phẩm 1", image: "/placeholder.svg" },
      { id: 2, title: "Tác phẩm 2", image: "/placeholder.svg" },
      { id: 3, title: "Tác phẩm 3", image: "/placeholder.svg" },
      { id: 4, title: "Tác phẩm 4", image: "/placeholder.svg" },
    ],
  },
  {
    id: 2,
    name: "Trần Thị B",
    specialty: "Nhạc cụ truyền thống",
    bio: "Nhạc sĩ chuyên về đàn tranh và đàn bầu. Giảng dạy tại nhiều trường âm nhạc.",
    fullBio: "Là một nghệ sĩ đàn tranh, tôi mong muốn mang âm nhạc truyền thống đến gần hơn với khán giả trẻ. Tôi kết hợp âm thanh cổ điển với những ảnh hưởng hiện đại để tạo ra một phong cách độc đáo.",
    image: "/placeholder.svg",
    coverImage: "/placeholder.svg",
    location: "TP. Hồ Chí Minh",
    followers: 856,
    rating: 4.8,
    verified: true,
    email: "tranthib@example.com",
    website: "tranthib.com",
    specialtyId: "music",
    works: [
        { id: 1, title: "Tác phẩm 1", image: "/placeholder.svg" },
        { id: 2, title: "Tác phẩm 2", image: "/placeholder.svg" },
        { id: 3, title: "Tác phẩm 3", image: "/placeholder.svg" },
        { id: 4, title: "Tác phẩm 4", image: "/placeholder.svg" },
    ],
  },
  {
    id: 3,
    name: "Lê Văn C",
    specialty: "Kiến trúc cổ",
    bio: "Kiến trúc sư chuyên về bảo tồn và phục dựng các công trình cổ Việt Nam.",
    fullBio: "Công việc của tôi là phục dựng lại những công trình kiến trúc cổ, từ những ngôi nhà cổ đến những ngôi đền, chùa. Tôi tin rằng việc bảo tồn kiến trúc là cách để chúng ta giữ gìn lịch sử và văn hóa.",
    image: "/placeholder.svg",
    coverImage: "/placeholder.svg",
    location: "Huế",
    followers: 567,
    rating: 4.7,
    verified: true,
    email: "levanc@example.com",
    website: "levanc.com",
    specialtyId: "architecture",
    works: [
        { id: 1, title: "Tác phẩm 1", image: "/placeholder.svg" },
        { id: 2, title: "Tác phẩm 2", image: "/placeholder.svg" },
        { id: 3, title: "Tác phẩm 3", image: "/placeholder.svg" },
        { id: 4, title: "Tác phẩm 4", image: "/placeholder.svg" },
    ],
  },
  {
    id: 4,
    name: "Phạm Thị D",
    specialty: "Gốm sứ truyền thống",
    bio: "Thợ gốm sứ từ làng Bát Tràng. Chuyên về kỹ thuật tạo hình và trang trí gốm.",
    fullBio: "Gốm sứ là niềm đam mê của tôi. Tôi lớn lên ở Bát Tràng và học nghề từ những người thợ giỏi nhất. Mỗi tác phẩm của tôi đều mang một câu chuyện và một phần tâm hồn của người thợ.",
    image: "/placeholder.svg",
    coverImage: "/placeholder.svg",
    location: "Bát Tràng",
    followers: 723,
    rating: 4.9,
    verified: true,
    email: "phamthid@example.com",
    website: "phamthid.com",
    specialtyId: "craft",
    works: [
        { id: 1, title: "Tác phẩm 1", image: "/placeholder.svg" },
        { id: 2, title: "Tác phẩm 2", image: "/placeholder.svg" },
        { id: 3, title: "Tác phẩm 3", image: "/placeholder.svg" },
        { id: 4, title: "Tác phẩm 4", image: "/placeholder.svg" },
    ],
  },
  {
    id: 5,
    name: "Hoàng Văn E",
    specialty: "Dệt vải truyền thống",
    bio: "Nghệ nhân dệt vải từ các dân tộc thiểu số. Bảo tồn kỹ thuật dệt truyền thống.",
    fullBio: "Tôi dệt vải bằng tay theo cách truyền thống của dân tộc mình. Mỗi tấm vải là một tác phẩm nghệ thuật, phản ánh văn hóa và cuộc sống của cộng đồng chúng tôi. Tôi muốn chia sẻ vẻ đẹp này với thế giới.",
    image: "/placeholder.svg",
    coverImage: "/placeholder.svg",
    location: "Sapa",
    followers: 445,
    rating: 4.8,
    verified: false,
    email: "hoangvane@example.com",
    website: "hoangvane.com",
    specialtyId: "craft",
    works: [
        { id: 1, title: "Tác phẩm 1", image: "/placeholder.svg" },
        { id: 2, title: "Tác phẩm 2", image: "/placeholder.svg" },
        { id: 3, title: "Tác phẩm 3", image: "/placeholder.svg" },
        { id: 4, title: "Tác phẩm 4", image: "/placeholder.svg" },
    ],
  },
  {
    id: 6,
    name: "Võ Thị F",
    specialty: "Chạm khắc gỗ",
    bio: "Nghệ nhân chạm khắc gỗ với kỹ thuật tinh xảo. Tác phẩm được trưng bày tại các bảo tàng.",
    fullBio: "Chạm khắc gỗ là một nghệ thuật đòi hỏi sự kiên nhẫn và tỉ mỉ. Tôi đã dành nhiều năm để hoàn thiện kỹ năng của mình. Các tác phẩm của tôi thường lấy cảm hứng từ thiên nhiên và văn hóa Việt Nam.",
    image: "/placeholder.svg",
    coverImage: "/placeholder.svg",
    location: "Hà Nội",
    followers: 892,
    rating: 4.9,
    verified: true,
    email: "vothif@example.com",
    website: "vothif.com",
    specialtyId: "craft",
    works: [
        { id: 1, title: "Tác phẩm 1", image: "/placeholder.svg" },
        { id: 2, title: "Tác phẩm 2", image: "/placeholder.svg" },
        { id: 3, title: "Tác phẩm 3", image: "/placeholder.svg" },
        { id: 4, title: "Tác phẩm 4", image: "/placeholder.svg" },
    ],
  },
];
